=== classicoman2/llmm-code/UD04-XML/2-DTD/clientes.dtd
<!ELEMENT cartera (cliente+)>
<!ELEMENT cliente (nombre, cif?, preferente?, diasentrega?, facturas?, vehicle)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT cif (#PCDATA)>
<!ELEMENT preferente EMPTY>
<!ELEMENT diasentrega (#PCDATA)>
<!ELEMENT facturas (factura+)>
<!ELEMENT factura (#PCDATA)>
<!ELEMENT vehicle (turisme|furgo|moto)>

<!ELEMENT turisme (#PCDATA)>
<!ELEMENT furgo (#PCDATA)>
<!ELEMENT moto (#PCDATA)>

=== classicoman2/llmm-code/UD04-XML/2-DTD/clientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cartera SYSTEM "clientes.dtd">
<cartera>
    <cliente>
        <nombre>Mercasa</nombre>
        <cif>5676443</cif>
        <preferente></preferente>
        <diasentrega>23-4-12</diasentrega>
        <vehicle>
            <moto></moto>
        </vehicle>
    </cliente>
    <cliente>
        <nombre>Acer SL</nombre>
        <cif>5121554</cif>
        <diasentrega>2-4-12</diasentrega>
     
        <facturas>
            <factura>5ip54</factura>
            <factura>599p94</factura>
            <factura>50p54</factura>
        </facturas>
        <vehicle>
            <moto></moto>
        </vehicle>
   
    </cliente>
</cartera>
