=== classicoman2/llmm-code/UD04-XML/02_DTD/clientes.dtd
<!ELEMENT clientes (cliente+)>
<!ELEMENT cliente (nombre, cif, preferente?, diasentrega?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT cif (#PCDATA)>
<!ELEMENT preferente EMPTY>
<!ELEMENT diasentrega (#PCDATA)>

=== classicoman2/llmm-code/UD04-XML/02_DTD/clientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clientes SYSTEM "clientes.dtd">
<clientes>
    <cliente>
        <nombre>Mercasa</nombre>
        <cif>5676443</cif>
        <preferente></preferente>
    </cliente>
    <cliente>
        <nombre>Acer SL</nombre>
        <cif>5121554</cif>
    </cliente>
</clientes>
