=== classicoman2/llmm-code/UD04-XML solucions exercicis/e04.2 DTD/operaciones.dtd
<!ELEMENT operaciones (operacion+)>
<!ELEMENT operacion (venta|compra)+>

<!ELEMENT venta (titulosvendidos)>
<!ELEMENT titulosvendidos (titulo+, cantidad, entregado?, importe)>


<!ELEMENT titulo (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT entregado EMPTY>
<!ELEMENT importe (#PCDATA)>
<!ATTLIST importe moneda CDATA #REQUIRED>

<!ELEMENT compra (tituloscomprados)>
<!ELEMENT tituloscomprados (titulo+, proveedor, fechacompra)>

<!-- no es pot repetir -->
<!-- <!ELEMENT titulo (#PCDATA)>  -->
<!ELEMENT proveedor (#PCDATA)>
<!ELEMENT fechacompra (dia, mes, año)>

<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT año (#PCDATA)>

=== classicoman2/llmm-code/UD04-XML solucions exercicis/e04.2 DTD/operaciones.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operaciones SYSTEM "operaciones.dtd">

<operaciones>
  <operacion>
      <venta>
          <titulosvendidos>
              <titulo>Don Quijote</titulo>
              <titulo>Rimas y leyendas</titulo>
              <cantidad>2000</cantidad>
              <importe moneda="euros">4400</importe>
          </titulosvendidos>
      </venta>
      <venta>
          <titulosvendidos>
              <titulo>Rinconete y Cortadillo</titulo>
              <titulo>Sainetes</titulo>
              <cantidad>1000</cantidad>
              <entregado/>
              <importe moneda="libras">290</importe>
          </titulosvendidos>
      </venta>
  </operacion>
  <operacion>
      <compra>
          <tituloscomprados>
              <titulo>De la Tierra a la Luna</titulo>
              <titulo>Barbarroja</titulo>
              <proveedor>Editorial EDSA</proveedor>
              <fechacompra>
                  <dia>10</dia>
                  <mes>6</mes>
                  <a単o>2018</a単o>
              </fechacompra>
          </tituloscomprados>
      </compra>
      <venta>
          <titulosvendidos>
              <titulo>Cinco semanas en globo</titulo>
              <titulo>Sainetes</titulo>
              <cantidad>700</cantidad>
              <entregado/>
              <importe moneda="euros">1490</importe>
          </titulosvendidos>
      </venta>
      <compra>
          <tituloscomprados>
              <titulo>De la Tierra a la Luna</titulo>
              <titulo>Barbarroja</titulo>
              <proveedor>Editorial Recopila</proveedor>
              <fechacompra>
                  <dia>2</dia>
                  <mes>12</mes>
                  <a単o>2017</a単o>
              </fechacompra>
          </tituloscomprados>
      </compra>
  </operacion>
</operaciones>
