=== classicoman2/llmm-code/UD04-XML solucions exercicis/e04.2 DTD/vendes.dtd
<!ELEMENT vendes (venda+)>
<!ELEMENT venda (vendacredit|vendaimmediata)>
<!ELEMENT vendacredit (datapagament?, quantitat)>
<!ELEMENT vendaimmediata (quantitat, divisa)>
<!ELEMENT datapagament (#PCDATA)>
<!ELEMENT quantitat (#PCDATA)>
<!ELEMENT divisa (#PCDATA)>

=== classicoman2/llmm-code/UD04-XML solucions exercicis/e04.2 DTD/vendes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vendes SYSTEM "vendes.dtd">
<vendes>
   <venda>
      <vendacredit>
         <quantitat>10.000</quantitat>
      </vendacredit>
   </venda>
   <venda>
      <vendaimmediata>
         <quantitat>5</quantitat>
         <divisa>euros</divisa>
      </vendaimmediata>
   </venda>
</vendes>
